platform :ios, '9.0'
use_frameworks!
target 'PrincekinPopoverViewDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    
    pod 'PrincekinPopoverView'
 end

